[package]
name = "rust-sidetracker-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
atproto_api = "=0.2.0"
dotenv = "=0.15.0"
openai = "1.0.0-alpha.18"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
